### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by DeprisAlexis** [CodedRed-Spigot/XpBottles#19]
Hello,
Will the plugin be updated to version 1.19.2?

Thank you in advance for your answer.

**Comment by Insprill** [comment]
1.19.2 support has been merged in for a little while now, just not released on Spigot. You can find a version built for 1.19.x in the #spigot-news channel of [CodedRed's Discord Server](https://discord.gg/gqwtqX3).

**Comment by CodedRedGIT** [comment]
https://github.com/CodedRed-Spigot/XpBottles/releases/tag/dev
